# Dockerfile für Kafka Connect mit ClickHouse Sink Connector
FROM confluentinc/cp-kafka-connect:7.5.0

# ClickHouse Connector JARs ins Plugin-Verzeichnis kopieren
COPY clickhouse-kafka-connect-v1.3.4/lib/* /etc/kafka-connect/jars/

# Lizenz und Doku
COPY clickhouse-kafka-connect-v1.3.4/doc/README.md /opt/clickhouse-connector-README.md
COPY clickhouse-kafka-connect-v1.3.4/doc/LICENSE /opt/clickhouse-connector-LICENSE

# Kopiere Connector-Konfiguration und Startskript ins Image
COPY config.json /kafka/connectors/config.json
# Keine Berechtigung um +x in /kafka zu setzen, x Flag bereits an Datei gesetzt
COPY start.sh /opt/start.sh
EXPOSE 8083
ENTRYPOINT ["/opt/start.sh"]
