# Apache Spark Dockerfile
FROM apache/spark:3.5.7-scala2.12-java11-python3-r-ubuntu

USER root
WORKDIR /app

COPY requirements.txt ./
RUN apt-get update && apt-get install -y gcc python3-dev librdkafka-dev python3-pip && \
    pip3 install --no-cache-dir -r requirements.txt

COPY main.py ./

CMD ["/opt/spark/bin/spark-submit", "main.py"]
