---
# ClickHouse Deployment
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: clickhouse
  namespace: {{ .Values.clickhouse.namespace }}
  labels:
    app: clickhouse
    component: db
spec:
  serviceName: clickhouse
  replicas: {{ .Values.clickhouse.replicaCount }}
  selector:
    matchLabels:
      app: clickhouse
      component: db
  volumeClaimTemplates:
    - metadata:
        name: clickhouse-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.clickhouse.storage.size }}
  template:
    metadata:
      labels:
        app: clickhouse
        component: db
    spec:
      containers:
      - name: clickhouse
        image: "{{ .Values.clickhouse.image.repository }}:{{ .Values.clickhouse.image.tag }}"
        imagePullPolicy: {{ .Values.clickhouse.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 8123
          protocol: TCP
        - name: native
          containerPort: 9000
          protocol: TCP
        env:
        - name: CLICKHOUSE_USER
          value: "admin"
        - name: CLICKHOUSE_PASSWORD
          value: "admin"
        volumeMounts:
        - name: clickhouse-data
          mountPath: /var/lib/clickhouse
        resources:
          limits:
            cpu: {{ .Values.clickhouse.resources.limits.cpu }}
            memory: {{ .Values.clickhouse.resources.limits.memory }}
          requests:
            cpu: {{ .Values.clickhouse.resources.requests.cpu }}
            memory: {{ .Values.clickhouse.resources.requests.memory }}

---
# ClickHouse Service
apiVersion: v1
kind: Service
metadata:
  name: clickhouse
  namespace: {{ .Values.clickhouse.namespace }}
  labels:
    app: clickhouse
    component: db
spec:
  type: ClusterIP
  ports:
  - port: 8123
    targetPort: http
    protocol: TCP
    name: http
  - port: 9000
    targetPort: native
    protocol: TCP
    name: native
  selector:
    app: clickhouse
    component: db
