---
# Kafka Connector für Clickhouse
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clickhouse-connector
  namespace: {{ .Values.kafkaConnect.namespace }}
  labels:
    app: clickhouse-connector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clickhouse-connector
  template:
    metadata:
      labels:
        app: clickhouse-connector
    spec:
      containers:
      - name: clickhouse-connector
        image: "{{ .Values.kafkaConnect.image.repository }}:{{ .Values.kafkaConnect.image.tag }}"
        imagePullPolicy: Never
        ports:
        - containerPort: 8083
        env:
        {{- range $key, $value := .Values.kafkaConnect.env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        resources:
          limits:
            cpu: {{ .Values.kafkaConnect.resources.limits.cpu | quote }}
            memory: {{ .Values.kafkaConnect.resources.limits.memory | quote }}
          requests:
            cpu: {{ .Values.kafkaConnect.resources.requests.cpu | quote }}
            memory: {{ .Values.kafkaConnect.resources.requests.memory | quote }}
---
apiVersion: v1
kind: Service
metadata:
  name: clickhouse-connector
  namespace: {{ .Values.kafkaConnect.namespace }}
spec:
  ports:
  - port: 8083
    targetPort: 8083
  selector:
    app: clickhouse-connector
