---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-connect
  namespace: {{ .Values.kafkaConnect.namespace }}
  labels:
    app: kafka-connect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-connect
  template:
    metadata:
      labels:
        app: kafka-connect
    spec:
      containers:
      - name: kafka-connect
        image: confluentinc/cp-kafka-connect:7.5.0
        ports:
        - containerPort: 8083
        env:
        - name: CONNECT_BOOTSTRAP_SERVERS
          value: {{ .Values.kafkaConnect.env.bootstrapServers | quote }}
        - name: CONNECT_REST_ADVERTISED_HOST_NAME
          value: "kafka-connect"
        - name: CONNECT_GROUP_ID
          value: "kafka-connect-group"
        - name: CONNECT_CONFIG_STORAGE_TOPIC
          value: "connect-configs"
        - name: CONNECT_OFFSET_STORAGE_TOPIC
          value: "connect-offsets"
        - name: CONNECT_STATUS_STORAGE_TOPIC
          value: "connect-status"
        - name: CONNECT_KEY_CONVERTER
          value: "org.apache.kafka.connect.storage.StringConverter"
        - name: CONNECT_VALUE_CONVERTER
          value: "org.apache.kafka.connect.json.JsonConverter"
        - name: CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE
          value: "false"
        - name: CONNECT_PLUGIN_PATH
          value: "/usr/share/java,/etc/kafka-connect/jars"
        volumeMounts:
        - name: clickhouse-sink-plugins
          mountPath: /etc/kafka-connect/jars
      volumes:
      - name: clickhouse-sink-plugins
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-connect
  namespace: {{ .Values.kafkaConnect.namespace }}
spec:
  ports:
  - port: 8083
    targetPort: 8083
  selector:
    app: kafka-connect
