
FROM python:3.13.9-slim-bookworm

# Metadata
LABEL description="FastAPI Ingestion Service für Sensor-Daten"

# Build Dependencies (benötigt für confluent-kafka Compilation)
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        gcc \
        g++ \
        linux-headers-amd64 \
        libffi-dev \
        librdkafka-dev \
    && rm -rf /var/lib/apt/lists/*

# Python Dependencies installieren
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Application Code
COPY main.py .

# Security: Non-root User
    RUN groupadd -g 1000 appuser && \
        useradd -m -u 1000 -g appuser appuser && \
        chown -R appuser:appuser /app

USER appuser

# Port exponieren
EXPOSE 8000

# Start Command
CMD ["python", "main.py"]
