{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: data-platform-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /api/rawdata
            pathType: Prefix
            backend:
              service:
                name: ingestion-api-service
                port:
                  number: {{ .Values.ingestionApi.service.port }}
          - path: /api/reports
            pathType: Prefix
            backend:
              service:
                name: reporting-api-service
                port:
                  number: {{ .Values.reportingApi.service.port }}
          - path: /grafana
            pathType: Prefix
            backend:
              service:
                name: grafana
                port:
                  number: 3000
{{- end }}
