apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.api }}
  labels:
    app.kubernetes.io/name: {{ .Values.global.platformName }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    component: api
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.messaging }}
  labels:
    app.kubernetes.io/name: {{ .Values.global.platformName }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    component: messaging
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.data }}
  labels:
    app.kubernetes.io/name: {{ .Values.global.platformName }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    component: data
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.monitoring }}
  labels:
    app.kubernetes.io/name: {{ .Values.global.platformName }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    component: monitoring
